# Use postgres/example user/password credentials
version: '3.1'
volumes:
   postgres-data:
      external: true
services:
   postgres_db:
      image: postgres
      restart: always
      container_name: psql-postgres-db
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: password
      ports:
         - 5432:5432
      volumes:
         - postgres-data:/var/lib/postgresql/data
   adminer:
      image: adminer
      restart: always
      container_name: psql-adminer
      ports:
         - 8081:8080
